[package]
name = "reconnecting-jsonrpsee-ws-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.29"
jsonrpsee = { version = "0.20.3", features = ["ws-client"] }
serde_json = { version = "1", features = ["raw_value"] }
tokio = { version = "1.35", features = ["rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tokio-retry = "0.3"
tracing = "0.1"

# optional dependencies
subxt = { version = "0.33", optional = true }

[dev-dependencies]
jsonrpsee = { version = "0.20.3", features = ["server"] }
anyhow = "1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
subxt = "0.33"
subxt-signer = "0.33"

[[example]]
name = "hello_subxt"
path = "examples/hello_subxt.rs"
required-features = ["subxt"]