[package]
name = "reconnecting-jsonrpsee-ws-client"
authors = ["Niklas Adolfsson <niklasadolfsson1@gmail.com>"]
version = "0.3.0"
edition = "2021"
rust-version = "1.64.0"
license = "MIT"
repository = "https://github.com/niklasad1/reconnecting-jsonrpsee-ws-client"
description = "jsonrpc-ws-client that reconnects automatically. Warning: It may lose subscription messages when reconnecting."
documentation = "https://docs.rs/reconnecting-jsonrpsee-ws-client"
keywords = ["jsonrpc", "json", "websocket"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
jsonrpsee = { version = "0.22", features = ["ws-client"] }
serde_json = { version = "1", features = ["raw_value"] }
tokio = { version = "1.35", features = ["rt-multi-thread", "sync"] }
tokio-stream = "0.1"
tokio-retry = "0.3"
tracing = "0.1"
thiserror = "1"

# optional dependencies
subxt = { version = "0.34", optional = true }

[features]
default = []
subxt = ["dep:subxt"]

[dev-dependencies]
jsonrpsee = { version = "0.22", features = ["server"] }
anyhow = "1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
subxt = "0.34"
subxt-signer = "0.34"

[[example]]
name = "hello_subxt"
path = "examples/hello_subxt.rs"
required-features = ["subxt"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
all-features = true
