[package]
name = "wasm-test"
publish = false
edition = "2021"
version = "0.1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.24"
tracing-wasm = "0.2.1"
console_error_panic_hook = "0.1.7"
reconnecting-jsonrpsee-ws-client = { path = "..", default-features = false, features = ["web"] }
